### ISSUE TITLE
Uncaught Unspecified Error Event (-72007)

### ISSUE THREAD

**Issue by rohailaltaf** [balthazar/react-native-zeroconf#45]
Occasionally, I have been getting the following error. I can not reproduce this reliably but it still happens enough times for it to be a problem. [Here's a screenshot](https://imgur.com/a/DnYAz).

Im not quite sure why the red screen is being shown even though I am catching errors using:

`zeroconf.on('error', (error) => { alert(error) });`
```
    try {
      zeroconf.scan(
        (type = 'http-nycts'),
        (protocol = 'tcp'),
        (domain = 'local.')
      );

    }
    catch(e) {
      //error
      alert(e);
    }
```

Is there a way to just suppress the screen for now till the error gets fixed?

**Comment by Apercu** [comment]
Looks like it's related to #23, is it when you put it to sleep too?

**Comment by rohailaltaf** [comment]
I checked #23 but this seems to be unrelated given that the app is active and running in the foreground with the screen unlocked

________________________________

**Comment by Apercu** [comment]
Can you take a look at [this](https://stackoverflow.com/a/39791849/2054072) maybe?

**Comment by RyanMitchellWilson** [comment]
I get this error ever single time I try to use it. Any fix for this yet?

**Comment by RyanMitchellWilson** [comment]
I found this on stack overflow https://stackoverflow.com/questions/10550137/what-cause-error-nsnetserviceserrorcode-72000.
This will tell you what those error codes actually mean. I was getting an error -72004 and that was because I was trying to pass in `_http` as the type. As soon as I switched that back to `http` I was able to get data back.

This may help narrow down what is actually happening.

**Comment by balthazar** [comment]
Looks like this error code refers to a timeout. The catch should work however.

**Comment by bitcrumb** [comment]
The issue situates itself on this line: https://github.com/balthazar/react-native-zeroconf/blob/master/src/index.js#L28

The `err` variabel is a string. However, when emitting an error event, the expected value is an Error object. This is asserted in the EventEmitter code (see: https://github.com/nodejs/node/blob/908292cf1f551c614a733d858528ffb13fb3a524/lib/events.js#L187).

I'll open a PR to fox this.

**Comment by bitcrumb** [comment]
Nevermind, I was on the wrong track. Apparently it is intended that the error is thrown... however it's not right that the error can't be catched. Is this due to EventEmitter being addressed directly instead of just throwing the error?

Isn't the proper fix to *not* use the EventEmitter & just throw a regular error in JS? This wat it can be catched...

/cc @balthazar

**Comment by bitcrumb** [comment]
@balthazar This fundamentally explains the issue why the errors can't be catched:

```try {
  setTimeout(() => {
    throw new Error("Won't be catched");
  }, 1000);
  throw new Error("Will be catched");
}
catch (e) {
  console.log("An error occured: " + ); // Will only execute for "Will be catched"
}``` 

With the difference that the `setTimeout` in the above example is actually an asynchronous event handler (registered on DeviceEmitter)  in the zeroconf library.

**Comment by digimatt22** [comment]
Has there been a resolution to this problem?

**Comment by ljbatwh** [comment]
Did a [PR]((https://github.com/balthazar/react-native-zeroconf/pull/158)) for this bug. @balthazar if you could give a review, it would be better
